// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0ortI9IXoKy5K4jA4w6uaKSXNZtIj1eA',
    appId: '1:863473392588:android:699b4f6ea130c771811b69',
    messagingSenderId: '863473392588',
    projectId: 'mychatap-65dc0',
    storageBucket: 'mychatap-65dc0.appspot.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCHWm7tWs6G6UwFd42VufuioP9gWBoP-HA',
    appId: '1:863473392588:web:3511990a15cc7459811b69',
    messagingSenderId: '863473392588',
    projectId: 'mychatap-65dc0',
    authDomain: 'mychatap-65dc0.firebaseapp.com',
    storageBucket: 'mychatap-65dc0.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBu1qaY1n3BIrBPhgzE2p_tG3z4raCgj-c',
    appId: '1:863473392588:ios:7efd0a9536a69e5c811b69',
    messagingSenderId: '863473392588',
    projectId: 'mychatap-65dc0',
    storageBucket: 'mychatap-65dc0.appspot.com',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBu1qaY1n3BIrBPhgzE2p_tG3z4raCgj-c',
    appId: '1:863473392588:ios:7efd0a9536a69e5c811b69',
    messagingSenderId: '863473392588',
    projectId: 'mychatap-65dc0',
    storageBucket: 'mychatap-65dc0.appspot.com',
    iosBundleId: 'com.example.mychatapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCHWm7tWs6G6UwFd42VufuioP9gWBoP-HA',
    appId: '1:863473392588:web:e36044dafcc76a6b811b69',
    messagingSenderId: '863473392588',
    projectId: 'mychatap-65dc0',
    authDomain: 'mychatap-65dc0.firebaseapp.com',
    storageBucket: 'mychatap-65dc0.appspot.com',
  );

}